#[derive(PartialEq)]
pub enum MessageType {
    RentRequest,
    ReturnRequest,
    RentConfirmed,
    RentRejected,
    ReturnConfirmed,
    ReturnRejected,
    StationUpdate,
    IsAlive,
    Election,
    Coordinator,
    Ack,
    NearbyResponse,
    PreparePayment,
    VoteCommit,
    VoteAbort,
    CommitPayment,
    CapturePayment,
    RollbackPayment,
    PaymentResult,
    NotReplica,
    Prepare,
    NotLeader,
    ReservePayment,
    ReservationRejected,
    OfflineRent,
    ReturnRent,
    UserBanned,
    BanNotification,
    ValidateUser,
    UserValidationResult,
}

impl MessageType {
    pub fn as_str(&self) -> &'static str {
        match self {
            Self::RentRequest => "RENT_REQUEST",
            Self::ReturnRequest => "RETURN_REQUEST",
            Self::RentConfirmed => "RENT_CONFIRMED",
            Self::RentRejected => "RENT_REJECTED",
            Self::ReturnConfirmed => "RETURN_CONFIRMED",
            Self::ReturnRejected => "RETURN_REJECTED",
            Self::StationUpdate => "STATION_UPDATE",
            Self::IsAlive => "IS_ALIVE",
            Self::Election => "ELECTION",
            Self::Coordinator => "COORDINATOR",
            Self::Ack => "ACK",
            Self::NearbyResponse => "NEARBY_RESPONSE",
            Self::PreparePayment => "PREPARE_PAYMENT",
            Self::VoteCommit => "VOTE_COMMIT",
            Self::VoteAbort => "VOTE_ABORT",
            Self::CommitPayment => "COMMIT_PAYMENT",
            Self::CapturePayment => "CAPTURE_PAYMENT",
            Self::RollbackPayment => "ROLLBACK_PAYMENT",
            Self::PaymentResult => "PAYMENT_RESULT",
            Self::NotReplica => "NOT_REPLICA",
            Self::Prepare => "PREPARE",
            Self::NotLeader => "NOT_LEADER",
            Self::ReservePayment => "RESERVE_PAYMENT",
            Self::ReservationRejected => "RESERVATION_REJECTED",
            Self::OfflineRent => "OFFLINE_RENT",
            Self::ReturnRent => "RETURN_RENT",
            Self::UserBanned => "USER_BANNED",
            Self::BanNotification => "BAN_NOTIFICATION",
            Self::ValidateUser => "VALIDATE_USER",
            Self::UserValidationResult => "USER_VALIDATION_RESULT",
        }
    }

    pub fn from_str(s: &str) -> Option<Self> {
        match s {
            "RENT_REQUEST" => Some(Self::RentRequest),
            "RETURN_REQUEST" => Some(Self::ReturnRequest),
            "RENT_CONFIRMED" => Some(Self::RentConfirmed),
            "RENT_REJECTED" => Some(Self::RentRejected),
            "RETURN_CONFIRMED" => Some(Self::ReturnConfirmed),
            "RETURN_REJECTED" => Some(Self::ReturnRejected),
            "STATION_UPDATE" => Some(Self::StationUpdate),
            "IS_ALIVE" => Some(Self::IsAlive),
            "ELECTION" => Some(Self::Election),
            "COORDINATOR" => Some(Self::Coordinator),
            "ACK" => Some(Self::Ack),
            "NEARBY_RESPONSE" => Some(Self::NearbyResponse),
            "PREPARE_PAYMENT" => Some(Self::PreparePayment),
            "VOTE_COMMIT" => Some(Self::VoteCommit),
            "VOTE_ABORT" => Some(Self::VoteAbort),
            "COMMIT_PAYMENT" => Some(Self::CommitPayment),
            "CAPTURE_PAYMENT" => Some(Self::CapturePayment),
            "ROLLBACK_PAYMENT" => Some(Self::RollbackPayment),
            "PAYMENT_RESULT" => Some(Self::PaymentResult),
            "NOT_REPLICA" => Some(Self::NotReplica),
            "PREPARE" => Some(Self::Prepare),
            "NOT_LEADER" => Some(Self::NotLeader),
            "RESERVE_PAYMENT" => Some(Self::ReservePayment),
            "RESERVATION_REJECTED" => Some(Self::ReservationRejected),
            "OFFLINE_RENT" => Some(Self::OfflineRent),
            "RETURN_RENT" => Some(Self::ReturnRent),
            "USER_BANNED" => Some(Self::UserBanned),
            "BAN_NOTIFICATION" => Some(Self::BanNotification),
            "VALIDATE_USER" => Some(Self::ValidateUser),
            "USER_VALIDATION_RESULT" => Some(Self::UserValidationResult),
            _ => None,
        }
    }
}
